export const routes = {
  home: "/",
  policy: "/privacy-policy",
  auth: {
    index: "/auth",
    login: "/auth/login",
    signup: "/auth/signup",
    verify: "/auth/verify/:id",
    onboarding: "/auth/onboarding",
    preview: "/auth/preview",
    complete: "/auth/complete",
    forgotPassword: "/auth/forgot-password",
  },
  app: {
    index: "/app",
    feed: "/app/feed",
    feed_auto_applied: "/app/feed?tab=applied",
    applications: "/app/applications",
    analytics: "/app/analytics",
    email: "/app/email",
    upskilling: "/app/upskilling",
    JobDetails: "/app/job/%id%",
    settings: "/app/settings",
    referral: "/app/referral",
  },
};
